import json

LANGS_MAPPING = { 
    "alsL": "als-Latn",
    "ara_Arab": "ara-Arab",
    "ast_Latn": "ast-Latn",
    "belC": "bel-Cyrl",
    "bosL": "bos-Latn", 
    "bulC": "bul-Cyrl",
    "catL": "cat-Latn",
    "cesL": "ces-Latn",
    "ckb_Arab": "ckb-Arab",
    "cmn_Hans": "cmn-Hans",
    "cymL": "cym-Latn",
    "danL": "dan-Latn",
    "deuL": "deu-Latn",
    "ekk_Latn": "ekk-Latn",
    "ellG": "ell-Grek",
    "engL": "eng-Latn",
    "spaL": "spa-Latn",
    "estL": "est-Latn",
    "eusL": "eus-Latn",
    "pesA": "pes-Arab",
    "faoL": "fao-Latn",
    "finL": "fin-Latn",
    "fraL": "fra-Latn",
    "glaL": "gla-Latn",
    "gleL": "gle-Latn",
    "glgL": "glg-Latn",
    "hrvL": "hrv-Latn",
    "bhrL": "bhr-Latn",
    "hebH": "heb-Hebr",
    "hinD": "hin-Deva",
    "hunL": "hun-Latn",
    "hyeA": "hye-Armn",
    "indL": "ind-Latn",
    "islL": "isl-Latn",
    "itaL": "ita-Latn",
    "jpnJ": "jpn-Jpan",
    "katG": "kat-Geor",
    "kmr_Latn": "kmr-Latn",
    "korH": "kor-Hang",
    "lim_Latn": "lim-Latn",
    "litL": "lit-Latn",
    "lvsL": "lvs-Latn",
    "ltzL": "ltz-Latn",
    "mkdC": "mkd-Latn",
    "mltL": "mlt-Latn",
    "nobL": "nob-Latn",
    "nldL": "nld-Latn",
    "nnoL": "nno-Latn",
    "polL": "pol-Latn",
    "porL": "por-Latn",
    "ronL": "ron-Latn",
    "rusC": "rus-Cyrl",
    "slkL": "slk-Latn",
    "slvL": "slv-Latn",
    "srpC": "srp-Cyrl",
    "sweL": "swe-Latn",
    "swhLatn": "swh-Latn",
    "tatC": "tat-Cyrl",
    "tam_Taml": "tam-Taml",
    "tha_Thai": "tha-Thai",
    "turL": "tur-Latn",
    "ukrC": "ukr-Cyrl",
    "vieL": "vie-Latn",
    "zhoH": "zho-Hans",
}

LANGS_MAPPING_IETF = { # https://en.wikipedia.org/wiki/IETF_language_tag
    "alsL": "sq",
    "astL": "ast",
    "belC": "be",
    "bosL": "bs", 
    "bulC": "bg",
    "catL": "ca",
    "cesL": "cs",
    "ckbA": "ku",
    "cymL": "cy",
    "danL": "da",
    "deuL": "de",
    "ellG": "el",
    "engL": "en",
    "spaL": "es",
    "ekkL": "et",
    "estL": "et",
    "eusL": "eu",
    "pesA": "fa",
    "faoL": "fo",
    "finL": "fi",
    "fraL": "fr",
    "glaL": "gd",
    "gleL": "ga",
    "glgL": "gl",
    "hrvL": "hr",
    "bhrL": "bs\n- hr",
    "hebH": "he",
    "hinD": "hi",
    "hunL": "hu",
    "hyeA": "hy",
    "indL": "id",
    "islL": "is",
    "itaL": "it",
    "jpnJ": "ja",
    "katG": "ka",
    "korH": "ko",
    "kmrL": "ku",
    "litL": "lt",
    "lvsL": "lv",
    "ltzL": "lb",
    "mkdC": "mk",
    "mltL": "mt",
    "nobL": "no",
    "nldL": "nl",
    "nnoL": "nn",
    "polL": "pl",
    "porL": "pt",
    "ronL": "ro",
    "rusC": "ru",
    "slkL": "sk",
    "slvL": "sl",
    "srpC": "sr",
    "sweL": "sv",
    "swhL": "sw",
    "tatC": "tt",
    "tamT": "ta",
    "thaT": "th",
    "turL": "tr",
    "ukrC": "uk",
    "vieL": "vi",
    "zhoH": "zh",
    "cmnH": "zh",
}


LANGUAGES = {}

with open("ISO-639-1-language.json") as f:
    lang_code2word = json.load(f)
for line in lang_code2word:
    code = line["code"]
    name = line["name"]
    LANGUAGES[code] = name
